apiVersion: v1
kind: ServiceAccount
metadata:
  name: tco-configurator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tco-configurator
rules:
- apiGroups: ["tco.io"]
  resources: ["teambudgets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tco.io"]
  resources: ["teambudgets/status"]
  verbs: ["patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tco-configurator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tco-configurator
subjects:
- kind: ServiceAccount
  name: tco-configurator
  namespace: default
